### ISSUE TITLE
イタリック体をPostScript文法で

### ISSUE THREAD

**Issue by t-tk** [obuk/use-groff#1]
fontforge を使用するという部分が少々手間がかかるので代案としてPostScript文法で作れないかと考えました。

単純に傾けるだけならPostScript文法で出来たはずと思い少々調べたら
gnuplot の term/PostScript/prologue.ps に Symbol から Symbol-Oblique を作る実例が見つかりました。
日本語フォントでも同様にできるようです。

```
/Ryumin-Light-Oblique-H /Ryumin-Light-H findfont [1 0 .167 1 0 0] makefont
dup length dict begin {1 index /FID eq {pop pop} {def} ifelse} forall
currentdict end definefont pop
%
100 80 moveto
/Ryumin-Light-Oblique-H findfont 70 scalefont setfont
(Id9f2=) show
```

R → 明朝体
I → 明朝の斜体
B → ゴシック体
BI → ゴシックの斜体
と割り当てることで fontforge を抜きに出来ないでしょうか。

**Comment by obuk** [comment]
イタリックは少し調べてみようと思いますが、fontforge を使わない選択は難しいと思います。というのは、groff のフォントは、最終的に afmtodit(1) を通して作成し、その入力として利用できる形に整えるところで fontforge を使っているからです。その1つに Adobe Glyph List (AGL) があり、これを含まないフォントもあれば、含むフォントもあり、fontforge で生成して整える、というわけです。

**Comment by obuk** [comment]
個人的なものかもしれませんが、私は日本語フォントの斜体に違和感があります。宜しければ「[斜体 読みにくい](https://www.google.com/search?q=斜体%20読みにくい)」もご参照ください。

私は、fontforge でフォントを変形して斜体を作りましたが、これは groff で斜体の切り替えをテストする場面でしか使っておりません。http://tug.ctan.org/info/mendex-doc/mendex.pdf も `\fI斜体\fP` とは書かず `〈斜体〉` と書いているように見えます。

斜体を作成しておきながら申し上げるというのは全く妙な話ですが、斜体は作成せず、ps.local は次のようなものがおすすめ、とするのは如何でしょうか。

```
.fspecial TR MR
.fspecial TI MR
.fspecial TB MB
.fspecial TBI MB
```

**Comment by t-tk** [comment]
> groff のフォントは、最終的に afmtodit(1) を通して作成し、その入力として利用できる形に整えるところで fontforge を使っているからです。

すみません。中身のことも分からず言っています。
かつての日本語groffもそうなのか、バックエンドが端末の場合もそうなのか、バックエンドにより fontforge を必要としない場合がないのか、などが分かりません。
バックエンドが PostScript のとき groff のフロントエンドはどうやって文字幅を知るのかも分かりません。

「日本語の斜体は読みにくい」説は私も実は賛成です。簡易的には斜体を無視してしまう方法も一つのやり方だと思います。また、現代は源ノ明朝、源ノ角ゴシックのようにウェイト・書体が異なるフリーの日本語フォントも利用できるようになっているのでそういうものを利用する方向(斜体を使わないで表現する方向)に進むべきと思います。
しかし、「I なり BI なりをその意味どおりに斜体で表現すべき」という考えもあると思います。
私としては一方に加担する気はない、といったところです。宗教戦争は避けたいです。

**Comment by obuk** [comment]
1. fontforge を必要としない場合がないのか

cjk の ttf を groff で利用するには、t42 と afm に 変換（fontforge/ttftot42）し、afm を groff のフォントに変換（afmtodit）します。

ttftot42 と fontforge のどちらも変換に利用できる場合もあれば、そうでない場合もあります。直した方が良いところがありましたら、pull req してください。

2. どうやって文字幅を知るのか。

groff フォントの charset 以降に以下のような行が並んでいます。

```
name metrics type code [entity_name] [-- comment]
```

その metrics にご質問の項目があります。

```
width[,height[,depth[,italic-correction
[,left-italic-correction[,subscript-correction]]]]]
```
詳細は groff_font(5) をご参照ください。

**Comment by t-tk** [comment]
ご解説ありがとうございます。参考になります。
本家groffソースの `font/devps/* ` を見てHelveticaなど各フォントのメトリック情報をテーブルで持っていることを確認しました。

日本語groffでは日本語フォント用に charset の仕様が拡張されているようです。おそらくAFMから得たものではなく「全角幅」のような概念からシンプルに作ったものと思います。

groff_1.18-1.1-12 の font/devps/M より
```
name M
internalname Ryumin-Light-EUC-H
spacewidth 250
encodingname EUC-JP
charset
u2E00..u9FFF 1000 3
uFF00..uFF5F 1000 3
uFF60..uFF9F 500 3
uFFA0..uFFEF 1000 3
```

上手に設計できれば、日本語groffの機能(もしくはその更に拡張)を本家groffに取り込んでもらえるようなパッチが作れるのではないか、と漠然と考えています。道のりは遠いですが。

**Comment by obuk** [comment]
比較のために AFM から作成したフォント（部分）を示します。

```
name MR
internalname IPAPMincho
special

charset
(snip)
u3041   819,665,57      2       2485    uni3041
u3042   899,812,37      2       2486    uni3042
u3043   859,555 0       2487    uni3043
u3044   959,671 2       2488    uni3044
u3045   689,655,64      2       2489    uni3045
u3046   740,814,34      2       2490    uni3046
u3047   790,658,43      2       2491    uni3047
u3048   870,808,14      2       2492    uni3048
u3049   810,629,24      2       2493    uni3049
u304A   910,770 2       2494    uni304A
u304B   950,774 2       2495    uni304B
u304B_3099      959,849 2       2496    uni304C
u304D   839,818,26      2       2497    uni304D
u304D_3099      899,861,26      2       2498    uni304E
u304F   700,813,43      2       2499    uni304F
u304F_3099      790,813,43      2       2500    uni3050
(snip)
```

**Comment by t-tk** [comment]
ありがとうございます。参考になります。
IPAP明朝でU+3041付近ということは、プロポーショナルフォントで丁度平仮名のプロポーショナルの領域ですね。
IPAP明朝でも漢字の部分はプロポーショナルではなく全角幅に統一されていて metrics の値が完全に同じまたはほぼ同じ行が延々と続いていると予想します。IPA明朝ならばプロポーショナル部分がほとんど無くさらに極端になると予想します。

何はともあれ全角ベタ組みが手軽に出来るようにするために、「同一のmetricsの繰り返しをUnicodeのコードポイントの範囲で指定する書式」をcharsetの文法に追加するような拡張をすれば日本語groffの機能に近づくような気がします。

**Comment by t-tk** [comment]
本家groffのgropsと日本語groffのgropsの差として、日本語groffでは最終的に `*-EUC-H` になるように文字コード変換している一方本家groffではその機能を欠いているようです。
上記の例ではおそらく `u3041`(文字コード, Unicodeのコードポイント)→`2485`(グリフID) の対応付けがその役割を果たしているのだと思います。
fontforge を必要としない方法のためにはこの差を埋める必要がありそうです。

**Comment by obuk** [comment]
grops(1) にフォントのインストール方法がまとまっています。そこには、groff が理解できるフォントは、AFM ファイルと PostScript Type 1 または Type 42 フォントで、変換には ttftot42 (または fontforge) と afmtodit を使うことが説明されています。詳細はマンページを参照して頂けるでしょうか。

**Comment by t-tk** [comment]
情報ありがとうございます。
[Wikipedia](https://ja.wikipedia.org/wiki/PostScript%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88#Type_42) によると PostScript Type 42 のバージョン 2015 以降で CJK TrueType fontを扱えるようになったとのこと。初めて知りました。少し時間を掛けて勉強しようと思います。

冒頭の私のただの思いつきは色々壁があることが分かりました。
ここは閉じましょうか？

**Comment by obuk** [comment]
t-tk さんの問題解決なら閉じて頂いても構いませんが、ご指摘の「イタリック体をPostScript文法で」はそのままになっています。もし気が向いたら pull req をお願いします。（メトリクスの作成もお願いします）

一連のお話の中に出てきた源ノ明朝と源ノ角ゴシックは、apt 等でインストールできるものは fontforge で扱えず、従って groff でも扱えません。しかし、https://github.com/fontforge/fontforge/issues/1582 から得られる otf は fontforge で扱えます。（ttftot42 の方は Invalid file format を出力します）

というわけで、いまのところ fontforge を使わないということも難しそうです。

**Comment by t-tk** [comment]
Type 42 フォントではなく CID フォントの書式を扱えるようにすれば私の目的に近づくような気がしています。それだとここの方法への機能拡張という形にはならないかもしれません。
具体的な道筋が見えてきて pull request が書けそうになったら再開することにして、今は閉じます。
ありがとうございました。

**Comment by t-tk** [comment]
ご無沙汰しております。
groffの公式最新版の grops で CIDフォントの書式をフォント非埋め込みで扱えるようにするパッチを書いてみました。
https://github.com/t-tk/groff-CJK-font

もしよろしかったらご覧ください。

**Comment by t-tk** [comment]
ご無沙汰しております。
groffの公式最新版の grops で CIDフォントの書式をフォント非埋め込みで扱えるようにするパッチを書いてみました。
https://github.com/t-tk/groff-CJK-font

もしよろしかったらご覧ください。

**Comment by obuk** [comment]
いまさら、という感じですが、洋画の字幕に縦書の斜体が使われているのを見て、
gropdfでTmオペレータを使用して、グリフを変形しました。https://github.com/obuk/gropdf-otf
CFFのサブセット化はpyftsubsetではうまく行かなくて、Font::TTF を修正して使いました。https://github.com/obuk/font-ttf
